version: '3.7'
services:
    php:
        build: .docker/php
        container_name: php-canadapost-api-php
        volumes:
          - .:/home/wwwroot/php-canadapost-api
        environment:
          - maildev_host=solexis-maildev
        networks:
          hostnet: {}
networks:
    hostnet:
        external: true
        name: sharednetwork
